# Use root/example as user/password credentials
version: "3.1"

volumes:
    sim:

services:
    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: sim
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
