on: push
name: 🚀 Deploy website on push
jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2.3.2

            - name: 🔨 Build Project
              run: |
                  composer install

            - name: 📂 Sync files
              uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
              with:
                  ftp_host: 5u6q7.ftp.infomaniak.com
                  ftp_username: 5u6q7_sim123klm
                  ftp_password: ${{ secrets.ftp_password }}
                  local_source_dir: ""
                  dist_target_dir: ""
                  delete: "false"
                  exclude: "'^logs/' '^README.md'"
